In [5]:
import tensorflow as tf

x = tf.constant(1, name='x')
y = tf.Variable(x+9,name='y')

In [7]:
model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

10


In [13]:
import tensorflow as tf
a=tf.placeholder("int32")
b=tf.placeholder("int32")
y=tf.multiply(a,b)
sess=tf.Session()
print(sess.run(y,feed_dict={a: 6, b: 5}))

30


190


In [1]:
import  tensorflow as tf
tf.conv

<tf.Tensor 'Abs:0' shape=() dtype=int32>

<tf.Tensor 'Abs:0' shape=() dtype=int32>

In [2]:
import tensorflow as tf
import numpy as np
tensor_1d=np.array([1,2,4])
tf_tensor_1d=tf.convert_to_tensor(tensor_1d,dtype=tf.float64)
print(tf_tensor_1d)
with tf.Session() as session:
     print(session.run(tf_tensor_1d))
     print(session.run(tf_tensor_1d[2]))

Tensor("Const_1:0", shape=(3,), dtype=float64)
[ 1.  2.  4.]
4.0


In [16]:
import  tensorflow as tf
import numpy as np
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32')
matrix2=np.array([(1,2,3),(2,3,5),(3,6,7)],dtype='int32')
print(matrix1)
tf_matrix1=tf.constant(matrix1)
tf_matrix2=tf.constant(matrix2)
print(tf_matrix1)
matrix_mul=tf.multiply(tf_matrix1,tf_matrix2)
print(matrix_mul)
matrix_add=tf.add(tf_matrix1,tf_matrix2)
print(matrix_add)
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32')
matrix_det = tf.matrix_determinant(matrix_3)
print(matrix_det)
with tf.Session() as sess:
     print(sess.run(matrix_det))
     print(sess.run(matrix_add))

[[2 2 2]
 [2 2 2]
 [2 2 2]]
Tensor("Const_22:0", shape=(3, 3), dtype=int32)
Tensor("Mul_9:0", shape=(3, 3), dtype=int32)
Tensor("Add_7:0", shape=(3, 3), dtype=int32)
Tensor("MatrixDeterminant_6:0", shape=(), dtype=float32)
56.0
[[3 4 5]
 [4 5 7]
 [5 8 9]]


In [17]:
import  tensorflow as tf
import numpy as np
matrix1 = np.array([(2,-3,2),(2,2,2),(2,-56,2)],dtype='int32')
matrix1_abs=tf.abs(matrix1)
with tf.Session() as sess:
    print(sess.run(matrix1_abs))

[[ 2  3  2]
 [ 2  2  2]
 [ 2 56  2]]


In [44]:
Y

array([[-2.   , -2.   , -2.   , ..., -2.   , -2.   , -2.   ],
       [-1.995, -1.995, -1.995, ..., -1.995, -1.995, -1.995],
       [-1.99 , -1.99 , -1.99 , ..., -1.99 , -1.99 , -1.99 ],
       ..., 
       [ 1.985,  1.985,  1.985, ...,  1.985,  1.985,  1.985],
       [ 1.99 ,  1.99 ,  1.99 , ...,  1.99 ,  1.99 ,  1.99 ],
       [ 1.995,  1.995,  1.995, ...,  1.995,  1.995,  1.995]])